version: '3.5'

services:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: nginx
                CONTAINER_VERSION: 1.0.6
                FROM_BASE: php5:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: nginx
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: nginx
        image: nginx:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 80:80
            - 443:443
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log
            - ./vols/www:/var/www
