version: '3.3'

# this is a SAMPLE file. Do not use for build or deployments

# use the following to restrict which OS this is built on
# containerOS: alpine

services:
    nginx-proxy:
# build arguments, only needed for building
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: nginx-proxy
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/nginx-base/${NGINX_VERSION:-1.15.3}:${BASE_TAG:-latest}
                SSL_ALREADY_GENERATED: 'true'
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.12.4}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/supervisord:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/nginx-base/${NGINX_VERSION:-1.15.3}:${BASE_TAG:-latest}
#                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/php/${PHP5_VERSION:-5.6.40-r0}:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: nginx-proxy
                version.cbf: $CBF_VERSION
        container_name: nginx-proxy
# common arguments, for building and deploy 
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            PWD_PROTECTED: 'true'
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: $CFG_USER
            WEB_USER_ID: $CFG_USER
            WEB_USER_PASS_FILE: /run/secrets/web_user.pwd
        hostname: nginx
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/nginx-proxy/${NGINX_VERSION:-1.15.3}:${CONTAINER_TAG:-latest}
# deploy arguments, not needed for building
        logging:                              # limit size of logs @runtime so that we do not run out of space 
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:                                #ports exposed 
            - 80:80
            - 443:443
        restart: unless-stopped               # only use when building a 'service container'
# references to 'secrets' section below
        secrets:
            - supervisord.pwd
            - web_user.pwd
            - certificate.crt
            - server.key
            - dhparam.pem
        volumes:
# application logs
            - ./vols/log:/var/log
# exposed web folder
            - ./vols/www:/var/www

secrets:
# location of secrets files in host filesystem
   supervisord.pwd:
     file: ~/.inf/secrets/bobb.password
   web_user.pwd:
     file: ~/.inf/secrets/bobb.password
   certificate.crt:
     file: ~/.inf/ssl/server.crt
   server.key:
     file: ~/.inf/ssl/server.key
   dhparam.pem:
     file: ~/.inf/ssl/dhparam.pem
