version: '3.3'

# repo: https://github/ballab1/nginx-proxy.git
# containerOS: alpine

services:
    nginx-proxy:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: nginx-proxy
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/nginx-base/${NGINX_VERSION:-1.15.3}:${BASE_TAG:-latest}
                SSL_ALREADY_GENERATED: 'true'
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}:${OS_VERSION:-3.8}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/supervisord:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/nginx-base/${NGINX_VERSION:-1.15.3}:${BASE_TAG:-latest}
#                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/php/${PHP5_VERSION:-5.6.37-r0}:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: nginx-proxy
                version.cbf: $CBF_VERSION
        container_name: nginx-proxy
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            PWD_PROTECTED: 'true'
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: $CFG_USER
            WEB_USER_ID: $CFG_USER
            WEB_USER_PASS_FILE: /run/secrets/web_user.pwd
        hostname: nginx
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/nginx-proxy/${NGINX_VERSION:-1.15.3}:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 80:80
            - 443:443
#        restart: unless-stopped
        secrets:
            - supervisord.pwd
            - web_user.pwd
            - certificate.crt
            - server.key
            - dhparam.pem
        volumes:
            - ./vols/log:/var/log
            - ./vols/www:/var/www

secrets:
   supervisord.pwd:
     file: ~/.inf/secrets/bobb.password
   web_user.pwd:
     file: ~/.inf/secrets/bobb.password
   certificate.crt:
     file: ~/.inf/ssl/server.crt
   server.key:
     file: ~/.inf/ssl/server.key
   dhparam.pem:
     file: ~/.inf/ssl/dhparam.pem
